#!/bin/bash

for i in $@; do
  test "$i" -gt 0 || {
    echo "$0: Inputs are not positive integers." >&2
    exit 1
  }
done

if [ ! $(($# % 2)) -eq 0 ]; then
  echo "$0: Odd number of arguments." >&2
  exit 1
fi

ccl -l /home/gabriel/Desktop/spiroffs-project/src/spiroffs-project.lx64fsl -e "(progn (hkm-main (list $*)) (ccl:quit))" | wolfram | sed -n -f /home/gabriel/Desktop/spiroffs-project/src/parse-output.sed
