#!/bin/bash

# Copyright (c) 2018, Gabriel Johnson. All rights reserved.

cd $(dirname "${BASH_SOURCE[0]}")

ccl="$(src/ccl-name)"

if [ ! $? -eq 0 ]; then
    echo "$0: fatal: No compatible CCL version found.">&2
    exit 1
fi

wolfram="$(src/wolfram-path)"

if [ ! $? -eq 0 ]; then
    echo "$0: fatal: Cannot determine where to find Mathematica.">&2
    exit 1
fi

test -f "$wolfram" || {
    echo "$0: Error: Mathematica kernel not found.">&2
    exit 1
}

"$ccl" -I hkm.image $*\
  | "$wolfram" -noprompt\
  | sed -e '1s/^/Hilbert-Kunz Multiplicity	= /' -e '2s/^/F-Signature			= /'

exit ${PIPESTATUS[0]}
