#!/bin/bash

ccl_path="ccl"
code_path="/home/gabriel/Desktop/spiroffs-project/src/spiroffs-project.lisp"

$ccl_path -I hkm.image $* | wolfram | sed -n -f /home/gabriel/Desktop/spiroffs-project/src/parse-output.sed
