#!/bin/bash

# Copyright (c) 2018, Gabriel Johnson. All rights reserved.

case $(uname) in
    Linux)
        ccl=ccl/lx86cl64
        ;;
    CYGWIN_NT-[[:digit:]]*.[[:digit:]]*)
        ccl=ccl/wx86cl64
        ;;
    Darwin)
        ccl=ccl/dx86cl64
        ;;
    *)
        echo "$0: Error: Unsupported operating system.">&2
        exit 1
        ;;
esac

cd $(dirname "${BASH_SOURCE[0]}")

$ccl -I hkm.image $*

exit $?
