#!/bin/bash

# Copyright (c) 2018, Gabriel Johnson. All rights reserved.

case $(uname) in
    Linux)
        kernel_path=/usr/local/bin/MathKernel
        ccl=ccl/lx86cl64
        ;;
    CYGWIN_NT-[[:digit:]]*.[[:digit:]]*)
        kernel_path="$(cygpath 'C:\Program Files\Wolfram Research\Mathematica\11.3\MathKernel')"
        ccl=ccl/wx86cl64
        ;;
    Darwin)
        kernel_path=/Applications/Mathematica.app/Contents/MacOS/MathKernel
        ccl=ccl/dx86cl64
        ;;
    *)
        echo "$0: Error: Unsupported operating system.">&2
        exit 1
        ;;
esac

test -f "$kernel_path" || {
    echo "$0: Warning: Mathematica kernel not found.">&2
    echo "Numerical values for the Hilbert-Kunz multiplicity and F-signature"\
         "cannot be calculated." >&2
}

cd $(dirname "${BASH_SOURCE[0]}")

test -f src/spiroffs-project.lisp || {
    echo "$0: Source code not found. Cannot compile." >&2
    exit 1
}

$ccl -l src/spiroffs-project.lisp \
  -e '(save-application "hkm.image" :toplevel-function #'\''main)' \
  && echo Done. || { echo "$0: Setup failed." >&2; exit 1; }
