#!/bin/bash

# Copyright (c) 2018, Gabriel Johnson. All rights reserved.

cd $(dirname "${BASH_SOURCE[0]}")

ccl="$(src/ccl-name)"

if [ ! $? -eq 0 ]; then
    echo "$0: fatal: No compatible CCL version found.">&2
    exit 1
fi

kernel_path="$(src/wolfram-path)"

if [ ! $? -eq 0 ]; then
    echo "$0: Warning: Cannot determine where to find Mathematica.">&2
fi

test -f "$kernel_path" || {
    echo "$0: Warning: Mathematica kernel not found.">&2
    echo "Numerical values for the Hilbert-Kunz multiplicity and F-signature"\
         "cannot be calculated." >&2
}

test -f src/spiroffs-project.lisp || {
    echo "$0: Source code not found. Cannot compile." >&2
    exit 1
}

"$ccl" -l src/spiroffs-project.lisp \
  -e '(save-application "hkm.image" :toplevel-function #'\''main)' \
  && echo Done. || { echo "$0: Setup failed." >&2; exit 1; }
